### PR TITLE
Adding possibility to load an HF-dataset

### PR DESCRIPTION
**Pull request by TevenLeScao**
Hello,

This PR creates a `load_dataset_hf.py` script that allows a user to start the process from an [HF dataset ](https://github.com/huggingface/datasets). This is an independent script as the parallelizing can be done natively with the `dataset.map` method rather than with the base Python `multiprocessing` module. The usage is the same as `load_dataset.py`, with an added `text_feature_key` argument in case the dataset stores its text in a column not named `text`. I can add a usage example to the README.md if that helps.

### CODE REVIEW

**Comment by TevenLeScao** [comment]
@googlebot I signed it!

**Comment by owos** [comment]
why has this not been merged yet though?

**Comment by carlini** [comment]
Merged; sorry for the delay. I wanted to have time to test things and don't have much free time, and finally set aside today to work my way through this repo.

**Comment by owos** [comment]
Thank you so much for doing this. I will try to use it on my end too. I believe that adding the huggingface feature will really make it easier for people to use this in their projects too.

**Pull request merged**
