### PR TITLE
Fix issue #45:out of range bug

### PR DESCRIPTION
**Pull request by WWWonderer**
See issue #45.

### CODE REVIEW

**Comment by carlini** [comment]
Your explanation and fix make sense to me. But I've been bitten enough times by "looks correct"....

Let me run a test on one of my ~10TB datasets just to make sure I get the same results before and after to make sure though. This shouldn't take too long, I'll post and update here when it finishes.

**Comment by WWWonderer** [comment]
Hi Nicholas, ok thank you!

**Comment by carlini** [comment]
I've confirmed this doesn't change results on my test case. Thanks, merged!

**Comment by WWWonderer** [comment]
Thank you so much!

**Pull request merged**
